name: Java CI with Maven - Test and package"

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 21
      
      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B compile package --file pom.xml

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonarqube-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-sonarqube-

      - name: Run SonarQube Scan
        env:
          GITHUB_TOKEN: ${{ secrets.CODE_DEPLOY }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B sonar:sonar -Dsonar.projectKey=my-project-key

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.CODE_DEPLOY }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B  verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=CERI-M1-DevOps_tpintegrationcontinue-Gasparfgf
